apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.rootUsername }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.rootPassword }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.database }}
