apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-node-app
  labels:
    app: {{ .Release.Name }}-node-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-node-app
    spec:
      containers:
        - name: node-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
